//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 08:24:16 PM ICT 
//


package com.viettelperu.qos.ws.wsdl.vascm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for wsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="checkedSubscriber" type="{http://ws.register.cm.viettel.com/}checkedSubscriber" minOccurs="0"/&gt;
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customer" type="{http://ws.register.cm.viettel.com/}customer" minOccurs="0"/&gt;
 *         &lt;element name="lstCustomer" type="{http://ws.register.cm.viettel.com/}customer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lstQuota" type="{http://ws.register.cm.viettel.com/}quota" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lstWSArea" type="{http://ws.register.cm.viettel.com/}wsArea" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lstWSReason" type="{http://ws.register.cm.viettel.com/}wsReason" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="lstWSSubscriber" type="{http://ws.register.cm.viettel.com/}wsSubscriber" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="paymentAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="wsArea" type="{http://ws.register.cm.viettel.com/}wsArea" minOccurs="0"/&gt;
 *         &lt;element name="wsSubscriber" type="{http://ws.register.cm.viettel.com/}wsSubscriber" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsResponse", propOrder = {
    "birthDate",
    "checkedSubscriber",
    "code",
    "customer",
    "lstCustomer",
    "lstQuota",
    "lstWSArea",
    "lstWSReason",
    "lstWSSubscriber",
    "message",
    "paymentAddress",
    "quota",
    "returnValue",
    "value",
    "wsArea",
    "wsSubscriber"
})
public class WsResponse {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar birthDate;
    protected CheckedSubscriber checkedSubscriber;
    protected String code;
    protected Customer customer;
    @XmlElement(nillable = true)
    protected List<Customer> lstCustomer;
    @XmlElement(nillable = true)
    protected List<Quota> lstQuota;
    @XmlElement(nillable = true)
    protected List<WsArea> lstWSArea;
    @XmlElement(nillable = true)
    protected List<WsReason> lstWSReason;
    @XmlElement(nillable = true)
    protected List<WsSubscriber> lstWSSubscriber;
    protected String message;
    protected String paymentAddress;
    protected Long quota;
    protected String returnValue;
    protected String value;
    protected WsArea wsArea;
    protected WsSubscriber wsSubscriber;

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the checkedSubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link CheckedSubscriber }
     *     
     */
    public CheckedSubscriber getCheckedSubscriber() {
        return checkedSubscriber;
    }

    /**
     * Sets the value of the checkedSubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckedSubscriber }
     *     
     */
    public void setCheckedSubscriber(CheckedSubscriber value) {
        this.checkedSubscriber = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the lstCustomer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstCustomer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstCustomer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Customer }
     * 
     * 
     */
    public List<Customer> getLstCustomer() {
        if (lstCustomer == null) {
            lstCustomer = new ArrayList<Customer>();
        }
        return this.lstCustomer;
    }

    /**
     * Gets the value of the lstQuota property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstQuota property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstQuota().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quota }
     * 
     * 
     */
    public List<Quota> getLstQuota() {
        if (lstQuota == null) {
            lstQuota = new ArrayList<Quota>();
        }
        return this.lstQuota;
    }

    /**
     * Gets the value of the lstWSArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstWSArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstWSArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsArea }
     * 
     * 
     */
    public List<WsArea> getLstWSArea() {
        if (lstWSArea == null) {
            lstWSArea = new ArrayList<WsArea>();
        }
        return this.lstWSArea;
    }

    /**
     * Gets the value of the lstWSReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstWSReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstWSReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsReason }
     * 
     * 
     */
    public List<WsReason> getLstWSReason() {
        if (lstWSReason == null) {
            lstWSReason = new ArrayList<WsReason>();
        }
        return this.lstWSReason;
    }

    /**
     * Gets the value of the lstWSSubscriber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lstWSSubscriber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLstWSSubscriber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsSubscriber }
     * 
     * 
     */
    public List<WsSubscriber> getLstWSSubscriber() {
        if (lstWSSubscriber == null) {
            lstWSSubscriber = new ArrayList<WsSubscriber>();
        }
        return this.lstWSSubscriber;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the paymentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAddress() {
        return paymentAddress;
    }

    /**
     * Sets the value of the paymentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAddress(String value) {
        this.paymentAddress = value;
    }

    /**
     * Gets the value of the quota property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuota() {
        return quota;
    }

    /**
     * Sets the value of the quota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuota(Long value) {
        this.quota = value;
    }

    /**
     * Gets the value of the returnValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnValue() {
        return returnValue;
    }

    /**
     * Sets the value of the returnValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnValue(String value) {
        this.returnValue = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the wsArea property.
     * 
     * @return
     *     possible object is
     *     {@link WsArea }
     *     
     */
    public WsArea getWsArea() {
        return wsArea;
    }

    /**
     * Sets the value of the wsArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsArea }
     *     
     */
    public void setWsArea(WsArea value) {
        this.wsArea = value;
    }

    /**
     * Gets the value of the wsSubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link WsSubscriber }
     *     
     */
    public WsSubscriber getWsSubscriber() {
        return wsSubscriber;
    }

    /**
     * Sets the value of the wsSubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsSubscriber }
     *     
     */
    public void setWsSubscriber(WsSubscriber value) {
        this.wsSubscriber = value;
    }

}
