//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 08:24:16 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.register.cm.viettel.com/")
package com.viettelperu.qos.ws.wsdl.vascm;
