//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 08:24:16 PM ICT 
//


package com.viettelperu.qos.ws.wsdl.vascm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.viettelperu.qos.ws.wsdl.vascm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CheckSubExistsActive_QNAME = new QName("http://ws.register.cm.viettel.com/", "checkSubExistsActive");
    private final static QName _CheckSubExistsActiveResponse_QNAME = new QName("http://ws.register.cm.viettel.com/", "checkSubExistsActiveResponse");
    private final static QName _ViewSubscriberByIsdn_QNAME = new QName("http://ws.register.cm.viettel.com/", "viewSubscriberByIsdn");
    private final static QName _ViewSubscriberByIsdnResponse_QNAME = new QName("http://ws.register.cm.viettel.com/", "viewSubscriberByIsdnResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.viettelperu.qos.ws.wsdl.vascm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckSubExistsActive }
     * 
     */
    public CheckSubExistsActive createCheckSubExistsActive() {
        return new CheckSubExistsActive();
    }

    /**
     * Create an instance of {@link CheckSubExistsActiveResponse }
     * 
     */
    public CheckSubExistsActiveResponse createCheckSubExistsActiveResponse() {
        return new CheckSubExistsActiveResponse();
    }

    /**
     * Create an instance of {@link ViewSubscriberByIsdn }
     * 
     */
    public ViewSubscriberByIsdn createViewSubscriberByIsdn() {
        return new ViewSubscriberByIsdn();
    }

    /**
     * Create an instance of {@link ViewSubscriberByIsdnResponse }
     * 
     */
    public ViewSubscriberByIsdnResponse createViewSubscriberByIsdnResponse() {
        return new ViewSubscriberByIsdnResponse();
    }

    /**
     * Create an instance of {@link WsRequest }
     * 
     */
    public WsRequest createWsRequest() {
        return new WsRequest();
    }

    /**
     * Create an instance of {@link WsResponse }
     * 
     */
    public WsResponse createWsResponse() {
        return new WsResponse();
    }

    /**
     * Create an instance of {@link CheckedSubscriber }
     * 
     */
    public CheckedSubscriber createCheckedSubscriber() {
        return new CheckedSubscriber();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link Quota }
     * 
     */
    public Quota createQuota() {
        return new Quota();
    }

    /**
     * Create an instance of {@link WsArea }
     * 
     */
    public WsArea createWsArea() {
        return new WsArea();
    }

    /**
     * Create an instance of {@link WsReason }
     * 
     */
    public WsReason createWsReason() {
        return new WsReason();
    }

    /**
     * Create an instance of {@link WsSubscriber }
     * 
     */
    public WsSubscriber createWsSubscriber() {
        return new WsSubscriber();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckSubExistsActive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.register.cm.viettel.com/", name = "checkSubExistsActive")
    public JAXBElement<CheckSubExistsActive> createCheckSubExistsActive(CheckSubExistsActive value) {
        return new JAXBElement<CheckSubExistsActive>(_CheckSubExistsActive_QNAME, CheckSubExistsActive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckSubExistsActiveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.register.cm.viettel.com/", name = "checkSubExistsActiveResponse")
    public JAXBElement<CheckSubExistsActiveResponse> createCheckSubExistsActiveResponse(CheckSubExistsActiveResponse value) {
        return new JAXBElement<CheckSubExistsActiveResponse>(_CheckSubExistsActiveResponse_QNAME, CheckSubExistsActiveResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewSubscriberByIsdn }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.register.cm.viettel.com/", name = "viewSubscriberByIsdn")
    public JAXBElement<ViewSubscriberByIsdn> createViewSubscriberByIsdn(ViewSubscriberByIsdn value) {
        return new JAXBElement<ViewSubscriberByIsdn>(_ViewSubscriberByIsdn_QNAME, ViewSubscriberByIsdn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewSubscriberByIsdnResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.register.cm.viettel.com/", name = "viewSubscriberByIsdnResponse")
    public JAXBElement<ViewSubscriberByIsdnResponse> createViewSubscriberByIsdnResponse(ViewSubscriberByIsdnResponse value) {
        return new JAXBElement<ViewSubscriberByIsdnResponse>(_ViewSubscriberByIsdnResponse_QNAME, ViewSubscriberByIsdnResponse.class, null, value);
    }

}
